const status = require("../server/enums/status")

module.exports = {
	MONGODB_CONNECTION: 'Mongodb connection established',
	UNAUTHORIZED: "User not authorized .",
	OTP_SEND: 'OTP send successfully.',
	OTP_RESEND: 'OTP resend successfully.',
	OTP_EXPIRED: 'OTP expired',
	NOT_OTP_VERIFY: 'OTP not verify',
	INCORRECT_OTP: 'Entered OTP is incorrect',
	BLOCK_BY_ADMIN: 'You have been blocked.',
	UNBLOCK_BY_ADMIN: 'You have been unblocked.',
	DELETE_BY_ADMIN: 'Your account has been deleted.',
	NO_TOKEN: 'Please provide token.',
	LOGIN: 'Login successfully',
	OTP_VERIFY: 'OTP verified successfully.',
	USER_ALREADY_EXIST: 'User already exist.',
	USER_NOT_FOUND: 'User not found.',
	ADMIN_NOT_FOUND: 'Admin not found.',
	REQUESTED_USER_NOT_FOUND: 'Requested user not found.',
	USER_NOT_VERIFIED: 'User not verified.',
	RECEIVER_NOT_FOUND: 'Receiver not found.',
	SENDER_NOT_FOUND: 'Sender not found.',
	USER_EXISTS: 'User Exists.',
	MOBILE_EXIST: 'This mobile number already exists.',
	EMAIL_EXIST: 'This email already exists.',
	USER_DETAILS: 'User details.',
	USER_CREATED: 'User created successfully.',
	USER_UPDATED: 'User updated successfully.',
	INCORRECT_LOGIN: 'Incorrect login credential provided.',
	OTP_NOT_VERIFY: 'Your account is not verified.',
	INCORRECT_SOCIAL_USER: 'User with social id exists, but the entered mobile number/email is incorrect.',
	NOT_REGISTERED: 'User not registered.',
	NOT_ACTIVATED: 'User not activated.',
	OLD_WRONG: "Old password is wrong.",
	PWD_CHANGED: 'Password has been changed successfully.',
	PWD_NOT_MATCH: 'Old password is incorrect',
	CWD_NOT_MATCH: 'Password and Confirm Password must match.',
	CMS_SAVED: 'Static content added successfully.',
	FAQ_ADDED: 'FAQ added successfully.',
	CONTACTUS_ADDED: 'ContactUs added successfully.',
	UPLOAD_SUCCESS: 'File uploaded successfully.',
	TRANSACTION_SUCCESS: 'Transaction has been completed.',
	DATA_FOUND: 'Data found successfully.',
	TRACKER_FOUND: 'Tracker Data found successfully.',
	DATA_NOT_FOUND: 'Data not found.',
	DETAILS_FETCHED: 'Details has been fetched successfully.',
	UPDATE_SUCCESS: 'Successfully updated.',
	ADDED_SUCCESS: 'Successfully added.',
	DELETE_SUCCESS: 'All notification deleted successfully.',
	DELETE_SUCCESS_EXPLORE: 'Deleted successfully.',
	USER_LOGOUT: 'User logged out successfully.',
	TWO_FA_GENERATED: 'Two factor authentication url generated successfully.',
	INCORRECT_CODE: 'Code expired, Please provide another one.',
	COLLECTION_NOT_FOUND: 'Collection Not Found.',
	ADD_NFT: 'Nft added successfully.',
	PROFILE_GET: 'Fetch profile data Successfully.',
	ADDRESS_ADD: 'Address added successfully.',
	MESSAGE_SEND: 'Message Send Successfully.',
	INTERNAL_ERROR: 'Internal Error.',
	NOT_FOUND: 'Not Found',
	FIELD_REQUIRED: 'Fields are required.',
	USER_BLOCKED: "User is Blocked.",
	USER_BLOCK: "User blocked successfully.",
	USER_ACTIVATED: "User is UnBlocked .",
	UPDATE_USER_PROFILE: "User profile updated successfully.",
	ACCOUNT_DELETE: "User Account deleted successfully.",
	DELETE_USER_PROFILE: "User profile deleted successfully.",
	USER_PROFILE_FOUND: "User profile found successfully.",
	USER_PROFILE_NOT_FOUND: "User profile not found.",
	USER_DELETE: 'User deleted successfully',
	USERS_FOUND: 'Users list found sucessfully',
	USERS_ALREADY_BLOCKED: 'User is already blocked',
	USERS_ALREADY_UNBLOCKED: 'User is already unblocked',
	USERS_UNBLOCKED: 'User unblocked successfully',
	APPROVAL_REQURIED: 'Your request has been submitted successfully. Please wait for admin approval.',
	ACCOUNT_APPROVED: 'Account has been successfully approved.',
	SESSION_EXPIRED: 'Session Expired, Please login again.',
	TEACHER_ASSIGNED: 'Teacher assigned sucessfully',
	STUDENT_NOT_FOUND: 'Student not found.',
	TEACHER_NOT_FOUND: 'Teacher not found.',
	ACCOUNT_APPROVAL: ' Your account has been approved by the admin. Please log in to start using the application and enjoy its features.',
	STUDENT_ASSIGNED: ' A student has been assigned to you.',
	ACCOUNT_VERIFICATION: ' Account Verification',
	ACCOUNT_VERIFICATION_REMINDER: ' Account Verification Reminder',
	ASSIGN_STUDENT_HEADING: 'Student Assigned',
	UNAPPROVED_USER_EMAIL: 'Email sent to admin for unapproved users.',
	NO_UNAPPROVED_USER_EMAIL: 'No unapproved users found.',
}